### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by lhahne** [netpyoung/fb-sdk-cljs#1]
Hi,

I am trying to use this library in my project. I added `[fb-sdk-cljs "0.1.0-SNAPSHOT"]` to my project.clj and it downloads ok. Then I try to require it like `[fb-sdk-cljs.core :as fb]` and my ide finds the files ok but when I try to compile my clojurescript files, I get:

WARNING: No such namespace: fb-sdk-cljs.core at line 1 src/cljs/test_project/core.cljs
WARNING: Required namespace not provided for fb-sdk-cljs.core

**Comment by netpyoung** [comment]
thank you for feedback. and sorry. i think that problem is caused by lack of my understanding about clojurescript library. now i'm on short trip. so i will check this issue on this sunday.

until then, add  `src/main/fb_sdk_cljs/core.cljs`, `resources/closure-js/externs/fb-sdk-cljs/facebook-jssdk.js` this file to your project.

again, i'm sorry about your inconvenience.

ps. In my memory, that warning doesn't effect on my project. so if you haven't time, try ignore that warning.

**Comment by netpyoung** [comment]
i switched from lein to boot. and i fixed this issue.

i'm so sorry for inconvinience.

[netpyoung/fb-sdk-cljs "0.1.1"]

**Comment by gamecubate** [comment]
Thanks for this! Works very well. Doc is a bit light but I got the information I needed by reading your test source.

**Comment by netpyoung** [comment]
@gamecubate I also happy to help you. I'm sorry for inconvenience lacked of documentation.
